wordpress_creds:
  host: http://localhost
  users:
    administrator:
      username: root
      password: root

ssh_creds:
  host: 192.168.100
  port: 22
  username: root
  password: root

wordpress_installation_path: clickandbuilds/projectwordpress/